name: Daily updates

on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - main

jobs:
  updates:
    name: Updates
    runs-on: ubuntu-latest
    steps:
      - name: Update this repo's README
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://charliewil.co/rss.xml
          readme-section: feed
          branch: main
          max: 5
          template: * [{{ title }}]({{ link }})
